### PR TITLE
BUG: Fix the loaded check for seg2nrrd

### PR DESCRIPTION
**Pull request by naucoin**
Enclose trying to access the seg2nrrd module in a try block,
otherwise the loading process will hang if the CLI module wasn't
loaded correctly.

### CODE REVIEW

**Comment by fedorov** [comment]
will you update the extension index?

**Comment by naucoin** [comment]
Sure!

**Comment by naucoin** [comment]
I don't have write access to the ExtensionsIndex github, I put in a pull request if you want to go ahead and merge it:
https://github.com/Slicer/ExtensionsIndex/pull/1189
and you did it before I could finish this comment, thanks!

**Comment by jcfr** [comment]
> I don't have write access to the ExtensionsIndex github

All set. @naucoin: you should be able to merge PR.

On Tue, Nov 24, 2015 at 4:02 PM, Nicole Aucoin <notifications@github.com>
wrote:

> I don't have write access to the ExtensionsIndex github, I put in a pull
> request if you want to go ahead and merge it:
> Slicer/ExtensionsIndex#1189
> <https://github.com/Slicer/ExtensionsIndex/pull/1189>
> and you did it before I could finish this comment, thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/QIICR/Reporting/pull/69#issuecomment-159404207>.
>



-- 
+1 919 869 8849

**Comment by naucoin** [comment]
@jcfr Thanks!

**Pull request merged**
